# Generated by Django 5.2.17 on 2026-09-23 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,12}$', 'A matrícula deve ter apenas números, entre 8 e 12 dígitos.')]),
        ),
    ]
