# Generated by Django 5.2.17 on 2026-09-20 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('reason_category', models.CharField(choices=[('Resposta incorreta', 'Resposta incorreta'), ('Enunciado ambiguo ou confuso', 'Enunciado ambiguo ou confuso'), ('Conteudo ofensivo ou inadequado', 'Conteudo ofensivo ou inadequado'), ('Pergunta duplicada', 'Pergunta duplicada'), ('Fora do tema', 'Fora do tema'), ('Outro', 'Outro')], max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='questions.question')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'reporter'), name='uq_reports_question_reporter')],
            },
        ),
    ]
