# Generated by Django 5.2.17 on 2026-09-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_fill_report_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason_category',
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
    ]
