# Generated by Django 5.2.17 on 2026-09-20 12:29

from django.conf import settings as dj_settings
from django.db import migrations, models


def seed_app_settings(apps, schema_editor):
    AppSettings = apps.get_model("core", "AppSettings")
    AppSettings.objects.get_or_create(
        pk=1,
        defaults={
            "similarity_threshold": dj_settings.SIMILARITY_THRESHOLD,
            "quiz_size": dj_settings.QUIZ_SIZE,
            "report_threshold": dj_settings.REPORT_THRESHOLD,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.FloatField()),
                ('quiz_size', models.PositiveIntegerField()),
                ('report_threshold', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_app_settings, migrations.RunPython.noop),
    ]
