# Generated by Django 5.2.17 on 2026-09-20 12:29

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('correct_answer', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('reported', 'Reportada'), ('removed', 'Removida')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='ix_questions_status'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ix_questions_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
