# Generated by Django 5.2.17 on 2026-09-21 01:27
# Ver 0002_clear_questions_for_model_switch.py para o motivo do split em duas
# migrations (Postgres nao permite DELETE + ALTER TABLE na mesma transacao).

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_clear_questions_for_model_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
