# Generated by Django 5.2.17 on 2026-09-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='citations_references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='pertinence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
