# Generated by Django 5.2.17 on 2026-09-24 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['user', 'answered_at'], name='ix_answer_user_time'),
        ),
    ]
